### ISSUE TITLE
Nothing is displayed after opening the EXE for a second. What should I do? Please help me!

### ISSUE THREAD

**Issue by AdmaXu** [mr-guard/dayz-server-manager#14] opened 2021-10-18 16:25 UTC
Nothing is displayed after opening the EXE for a second. What should I do? Please help me!

**Comment by mr-guard** [comment] 2021-10-20 07:42
yes, you should do that

**Comment by Kirill246** [comment] 2022-01-18 05:03
Perhaps the problem is in the editor, my server started to start only after I used notepad ++, when using other editors with the same changes, the server did not start.

**Comment by mr-guard** [comment] 2022-01-18 08:49
That indicates an issue with fileencoding/line endings

Anyways, the issue mentioned here is that the server manager closed because it was opened by double clicking on it in the file explorer

this should be fixed now

**Closed** 2023-07-06 13:41 UTC
