### ISSUE TITLE
get stuck on step“Checking/Installing SteamCMD”

### ISSUE THREAD

**Issue by onlinylee** [mr-guard/dayz-server-manager#61] opened 2023-09-13 08:47 UTC
Described as follows:
1. SteamCMD successfully installed and updated;
2. DayZsever successfully installed and updated;
3. Game server and web console were successfully running many time over;
4. But now stopped short, getting stuck, why?

It's my problem or not, need help, plz

![Snipaste_2023-09-13_16-59-27](https://github.com/mr-guard/dayz-server-manager/assets/90897703/52b18cb8-7758-4b1e-af06-2386285b90d8)

[server-manager.log](https://github.com/mr-guard/dayz-server-manager/files/12595409/server-manager.log)

**Comment by mr-guard** [comment] 2023-09-14 16:34
Can you retry with the newest version (v3.1.0)?

**Comment by onlinylee** [comment] 2023-09-15 15:20
Ok sir, already downloaded, I'll follow up with test results here later

**Comment by mr-guard** [comment] 2023-09-17 09:28
Is it working?

**Comment by lapochka8** [comment] 2023-09-28 00:28
having the same issue with the latest version. Verifying installation

**Comment by onlinylee** [comment] 2023-09-28 04:01
Sir, I tested 3.10 and 3.20, issue remains, it seems to have something to do with SteamCMD, but if run it alone, everything works fine.
1.Modify config and add steam account(DayZ owned) follow run dayz-server-manager-3.2.0.exe, this step OK until SteamCMD installed will get stuck, check root  have "DayZServer"floder size just 20-30kb
2.Independently executing "SteamCMD\steamcmd.exe" login steam account(DayZ owned) , execution“force_install_dir ./dayz_ds/”and "app_update 223350 validate" get dayzs erver latest version, copy to root "DayZServer"
3.Launch dayz-server-manager(3.2.0).exe got stuck, type "Verifying installation"

**Comment by mr-guard** [comment] 2023-09-28 14:58
I cannot reproduce the error unfortunately 

It might be a permission thing

can you try doing it on a folder on your desktop?
maybe try running as admin?

**Comment by cigaming** [comment] 2023-10-01 05:35
![image](https://github.com/mr-guard/dayz-server-manager/assets/35055680/9482f7e4-c496-4c03-83d6-1843cf37945b)
I am having the same issue both running as admin and running normal. Windows server 2022 and checked perms and the admin account has full perms

**Comment by mr-guard** [comment] 2023-10-01 14:19
Would you mind testing it on your local pc?

Might be a windows server specific thing
If you run into the same issue on your local pc, then enable debug logs (loglevel = 0) and send me the logs via pm in discord

**Comment by cigaming** [comment] 2023-10-01 15:11
Found the issue its getting hung up on the two factor when I add in my steam user name and password
However it will not let me enter my 2FA code
![image](https://github.com/mr-guard/dayz-server-manager/assets/35055680/7db7deeb-a21a-462b-b480-ee86b8e343c9)

**Comment by cigaming** [comment] 2023-10-01 15:22
here is the pastebin of the logs
https://pastebin.com/tm6kEGsJ

also whats your discord name

**Comment by onlinylee** [comment] 2023-10-04 13:16
First time I used dayz-server-manager version is 3.0.1
At that time everything was working fine, I can launch dayz server and web, but now any version will not work, I don't think it's necessarily your fault, but I couldn't find the reason myself, so I had to keep giving feedback.
I recently started using a virtual machine system and tested it in windows server 2022 with the same results.

**Comment by mr-guard** [comment] 2023-10-04 14:49
Just in case: If you have Steam Guard enabled, you need to DISABLE IT. Otherwise the manager will wait for you to input the code which does not work.

**Comment by onlinylee** [comment] 2023-10-06 14:26
Sir sir sir~u r right~I did turn on email verification recently, problem solved, everything is ok

**Comment by mr-guard** [comment] 2023-10-06 17:23
I will close this as solved then

Will include that in the readme soonish :)

**Closed by mr-guard** 2023-10-06 17:23 UTC
