### ISSUE TITLE
Failure while copy Mod Keys (unlink)

### ISSUE THREAD

**Issue by Kernol12** [mr-guard/dayz-server-manager#51] opened 2023-05-02 19:56 UTC
![grafik](https://user-images.githubusercontent.com/57406152/235761976-3c281cbf-67fc-4275-80fd-291a785ff78b.png)

Does some one know how to fix my error. I tried already to remove all the Key duplicates.

**Comment by radixtenshi** [comment] 2023-05-17 07:23
yes, i solve it deleting the mod folder. I mean the folder with the name @MOD inside the DayZServer folder. I think in this case is the folder @CJ187_Drinks_Food

The manager will redownload or recopy the folder from workshop.

If that not work, could be the steamCMD working bad, in some very rare cases you need to delete the steamCMD folder (make backup) and download it again (and re login again).

**Comment by mr-guard** [comment] 2023-07-06 13:16
Found the issue..
Some mods provide the same key. The manager tries to copy them all at once, which then causes conflicts.

Will be fixed in a future update

**Comment by mr-guard** [comment] 2023-07-06 13:47
Duplicate of #40

**Closed by mr-guard** 2023-07-06 13:47 UTC
